# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

PUT {{apiAddress}}/approval-holiday
Content-Type: application/json

{
  "applicant": "li.dongxun",
  "holidayStartAt": "2019-06-01",
  "holidayEndAt": "2019-06-16",
  "reason": "첫째아기 병원",
  "approver": "ahn.younghoe"
}

###
GET {{apiAddress}}/approval-holiday?id=1
Accept: application/json

###